// <auto-generated />
namespace SharpRepository.Samples.MVC5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialContacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialContacts));
        
        string IMigrationMetadata.Id
        {
            get { return "201710301135311_InitialContacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
