//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpRepository.Tests.Integration.DynamicProxyObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SharpRepositoryTestEntities : DbContext
    {
        public SharpRepositoryTestEntities()
            : base("name=SharpRepositoryTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MainItem> MainItems { get; set; }
        public DbSet<SomeObject> SomeObjects { get; set; }
        public DbSet<SomeType> SomeTypes { get; set; }
    }
}
