//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpRepository.Tests.Integration.DynamicProxyObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SomeType
    {
        public SomeType()
        {
            this.MainItems = new HashSet<MainItem>();
            this.SomeObjects = new HashSet<SomeObject>();
        }
    
        public int SomeTypeId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<MainItem> MainItems { get; set; }
        public virtual ICollection<SomeObject> SomeObjects { get; set; }
    }
}
