//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpRepository.Tests.Integration.DynamicProxyObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class SomeObject
    {
        public int SomeObjectId { get; set; }
        public int SomeTypeId { get; set; }
        public string Title { get; set; }
    
        public virtual SomeType SomeType { get; set; }
    }
}
